spring.application.name=RadioManagement
logging.level.org.springframework.security=DEBUG

spring.datasource.url=jdbc:postgresql://localhost:5432/radio_management
spring.datasource.username=radio_user
spring.datasource.password=radio_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false